### ISSUE TITLE
Errors during building

### ISSUE THREAD

**Issue by spectrwm** [guayom/hugo-taxonomies#2]
$ hugo server
Building sites … ERROR 2022/10/09 09:38:20 render of "page" failed: execute of template failed: template: _default/single.html:6:7: executing "main" at <partial "brand-list.html" .>: error calling partial: "/home/asp/Desktop/hugo-taxonomies-master/layouts/partials/brand-list.html:7:16": execute of template failed: template: partials/brand-list.html:7:16: executing "partials/brand-list.html" at <$.Site.GetPage>: error calling GetPage: too many arguments to .Site.GetPage: [taxonomyTerm brands adidas]. Use lookups on the form {{ .Site.GetPage "/posts/mypage-md" }}
ERROR 2022/10/09 09:38:20 render of "page" failed: execute of template failed: template: _default/single.html:6:7: executing "main" at <partial "brand-list.html" .>: error calling partial: "/home/asp/Desktop/hugo-taxonomies-master/layouts/partials/brand-list.html:7:16": execute of template failed: template: partials/brand-list.html:7:16: executing "partials/brand-list.html" at <$.Site.GetPage>: error calling GetPage: too many arguments to .Site.GetPage: [taxonomyTerm brands asics]. Use lookups on the form {{ .Site.GetPage "/posts/mypage-md" }}
ERROR 2022/10/09 09:38:20 render of "page" failed: execute of template failed: template: _default/single.html:6:7: executing "main" at <partial "brand-list.html" .>: error calling partial: "/home/asp/Desktop/hugo-taxonomies-master/layouts/partials/brand-list.html:7:16": execute of template failed: template: partials/brand-list.html:7:16: executing "partials/brand-list.html" at <$.Site.GetPage>: error calling GetPage: too many arguments to .Site.GetPage: [taxonomyTerm brands asics]. Use lookups on the form {{ .Site.GetPage "/posts/mypage-md" }}
ERROR 2022/10/09 09:38:20 render of "page" failed: execute of template failed: template: _default/single.html:6:7: executing "main" at <partial "brand-list.html" .>: error calling partial: "/home/asp/Desktop/hugo-taxonomies-master/layouts/partials/brand-list.html:7:16": execute of template failed: template: partials/brand-list.html:7:16: executing "partials/brand-list.html" at <$.Site.GetPage>: error calling GetPage: too many arguments to .Site.GetPage: [taxonomyTerm brands asics]. Use lookups on the form {{ .Site.GetPage "/posts/mypage-md" }}
ERROR 2022/10/09 09:38:20 render of "page" failed: execute of template failed: template: _default/single.html:6:7: executing "main" at <partial "brand-list.html" .>: error calling partial: "/home/asp/Desktop/hugo-taxonomies-master/layouts/partials/brand-list.html:7:16": execute of template failed: template: partials/brand-list.html:7:16: executing "partials/brand-list.html" at <$.Site.GetPage>: error calling GetPage: too many arguments to .Site.GetPage: [taxonomyTerm brands new-balance]. Use lookups on the form {{ .Site.GetPage "/posts/mypage-md" }}
Built in 90 ms
Error: Error building site: failed to render pages: render of "taxonomyTerm" failed: "/home/asp/Desktop/hugo-taxonomies-master/layouts/_default/terms.html:36:21": execute of template failed: template: _default/terms.html:36:21: executing "main" at <$.Site.GetPage>: error calling GetPage: too many arguments to .Site.GetPage: [taxonomyTerm brands new-balance]. Use lookups on the form {{ .Site.GetPage "/posts/mypage-md" }}

How to fix?

**Comment by dzwiedziu-nkg** [comment]
Confirm. Not working with Hugo v0.108

**Comment by dravecca00** [comment]
Try this to avoid "too many arguments on Site.GetPage" problem

{{ $path := printf "/brands/%s" $brand }}
{{ range ($.Site.GetPage $path).Pages }}

Change on "partials/brand-list.html" and "_default/terms.html"
